# Generated by Django 4.0.5 on 2022-06-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
