# Generated by Django 4.0.5 on 2022-06-22 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0004_creditor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditor_account', to='loan.customeraccount'),
        ),
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_amount', models.FloatField(blank=True, default=0, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='loan.customeraccount')),
                ('loans', models.ManyToManyField(blank=True, to='loan.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debtor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='creditor',
            name='debtors',
            field=models.ManyToManyField(to='loan.debtor'),
        ),
    ]
