# Generated by Django 4.0.5 on 2022-06-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0005_alter_creditor_account_debtor_creditor_debtors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditor',
            name='credit_given',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='credit_paid',
            field=models.FloatField(default=0),
        ),
    ]
