# Generated by Django 4.0.5 on 2022-06-22 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0008_debtor_due_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditor',
            name='debtors',
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='creditors',
            field=models.ManyToManyField(related_name='creditors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customeraccount',
            name='debtors',
            field=models.ManyToManyField(related_name='debtors', to=settings.AUTH_USER_MODEL),
        ),
    ]
