# Generated by Django 4.0.5 on 2022-06-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_alter_loan_borrower_alter_loan_lender'),
        ('loan', '0009_remove_creditor_debtors_customeraccount_creditors_and_more'),
    ]

    operations = [
    ]
