# Generated by Django 4.0.5 on 2022-06-22 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0010_alter_loan_lender'),
        ('loan', '0010_merge_20220622_1930'),
    ]

    operations = [
    ]
