# Generated by Django 4.0.5 on 2022-06-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_alter_loan_borrower_alter_loan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
    ]
