# Generated by Django 4.0.5 on 2022-06-23 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan', '0016_alter_transaction_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraccount',
            name='creditors',
            field=models.ManyToManyField(blank=True, related_name='creditors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customeraccount',
            name='debtors',
            field=models.ManyToManyField(blank=True, related_name='debtors', to=settings.AUTH_USER_MODEL),
        ),
    ]
