# Generated by Django 4.0.5 on 2022-06-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0017_alter_customeraccount_creditors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='message',
            field=models.CharField(default='Default', max_length=255),
            preserve_default=False,
        ),
    ]
