# Generated by Django 4.0.5 on 2022-06-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0019_alter_transaction_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ('-payment_date',)},
        ),
    ]
